I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00gamemenu.rpy", line 173, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 173, in <module>
    $ ui.interact()
  File "game/screens.rpy", line 646, in execute
    screen save():
  File "game/screens.rpy", line 646, in execute
    screen save():
  File "game/screens.rpy", line 650, in execute
    use file_slots(_("Save"))
  File "game/screens.rpy", line 660, in execute
    screen file_slots(title):
  File "game/screens.rpy", line 660, in execute
    screen file_slots(title):
  File "game/screens.rpy", line 666, in execute
    fixed:
  File "game/screens.rpy", line 766, in execute
    if renpy.get_screen("save"):
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00gamemenu.rpy", line 173, in script
    $ ui.interact()
  File "C:\Users\00gly\Documents\Renpy\renpy\ast.py", line 881, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\00gly\Documents\Renpy\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00gamemenu.rpy", line 173, in <module>
    $ ui.interact()
  File "C:\Users\00gly\Documents\Renpy\renpy\ui.py", line 289, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\00gly\Documents\Renpy\renpy\display\core.py", line 2672, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\00gly\Documents\Renpy\renpy\display\core.py", line 3059, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\00gly\Documents\Renpy\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\00gly\Documents\Renpy\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\00gly\Documents\Renpy\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\00gly\Documents\Renpy\renpy\display\core.py", line 531, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\00gly\Documents\Renpy\renpy\display\screen.py", line 424, in visit_all
    callback(self)
  File "C:\Users\00gly\Documents\Renpy\renpy\display\core.py", line 3059, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\00gly\Documents\Renpy\renpy\display\screen.py", line 434, in per_interact
    self.update()
  File "C:\Users\00gly\Documents\Renpy\renpy\display\screen.py", line 619, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 646, in execute
    screen save():
  File "game/screens.rpy", line 646, in execute
    screen save():
  File "game/screens.rpy", line 650, in execute
    use file_slots(_("Save"))
  File "game/screens.rpy", line 660, in execute
    screen file_slots(title):
  File "game/screens.rpy", line 660, in execute
    screen file_slots(title):
  File "game/screens.rpy", line 666, in execute
    fixed:
  File "game/screens.rpy", line 766, in execute
    if renpy.get_screen("save"):
  File "C:\Users\00gly\Documents\Renpy\renpy\sl2\slast.py", line 804, in execute
    imc = renpy.ui.imagemap_stack[-1]
IndexError: list index out of range

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
SyntheticLover 1.0
Tue Dec 25 02:24:23 2018
